#!/bin/bash

#
# Parse server and browser logs and pretty print the server name and request/response strings
#
# Usage: parselogs {browser log} {server log}
#

# List requests issued by the client
echo ''
echo 'BROWSER REQUESTS SENT'
awk -F';' '/REQ/ {print $7 "\t" $11}' $1

# List responses received by the client
echo ''
echo 'BROWSER RESPONSES RECEIVED'
awk -F';' '/RESP/ {print $6 "\t" $11}' $1

# List requests received by the server
echo ''
echo 'SERVER REQUESTS RECEIVED'
awk -F';' '/REQ/ {print $7 "\t" $11}' $2

# List responses issued by the server
echo ''
echo 'SERVER RESPONSES SENT'
awk -F';' '/RESP/ {print $6 "\t" $11}' $2
