
# Get a single page - no resources
3600;www.single.org

# Get a page with resources - four images expected
7200;www.single.org/photos

# A cross browse request - the page requested contains references to a number of resources from a 3rd party site.
10800;www.single.org/cross

# A series of bad browse requests - non-existent pages on the www.single.org server
14400;www.single.org/development
14700;www.single.org/finances
15000;www.single.org/users
15300;www.single.org/topsecret

